### ISSUE TITLE
fetching stuff sometimes throws JSON parse error on timeout

### ISSUE THREAD

**Issue by nick-delirium** [LemmyNet/lemmy-js-client#141]
<img width="527" alt="image" src="https://github.com/LemmyNet/lemmy-js-client/assets/23126999/818a476c-d4c1-4d43-b92e-d601923e9e76">

testing this inside react-native app right now. I opened related issue on main repo about long time to get voting request handled and noticed this as well.

**Comment by pascaldevink** [comment]
@nick-delirium Do you have a request to reproduce this with? And do you know what the response is that is returned? It seems a JSON response was expected, but I've noticed sometimes a request results in a 304 to another (non-api) page, which then results in this behaviour.

**Comment by nick-delirium** [comment]
@pascaldevink tried couple times, looks like it was tied to long requests from DB locks situation in one of 0.17 sub releases, right now I can't actually reproduce this behavior.

Requests that used to return this error was `likePost`

**Comment by IggsGrey** [comment]
It looks like the http helper/wrapper was written with the intent that the server response is always JSON data.
Reference: https://github.com/LemmyNet/lemmy-js-client/blob/0a9c151b8ec492228b6bfd37d395567a170c18cb/src/http.ts#L1328

Since we're always expecting a correct response to be JSON data, does it make sense that we rule out all non-JSON data as errors?

**Comment by nick-delirium** [comment]
well, I'm pretty sure that even if backend will be 100% covered to return JSON all the time, no one is safe from timeouts, nginx fails etc, so it should have try catch for this case as well
