### ISSUE TITLE
`Person.inbox_url` should be optional

### ISSUE THREAD

**Issue by TheBrokenRail** [LemmyNet/lemmy-js-client#179]
`Person.inbox_url` is specified as [always non-null](https://github.com/LemmyNet/lemmy-js-client/blob/406d1c187bd4bd13203cfd41ea1c8872e69aae3f/src/types/Person.ts#L18).

However, it is easy to discover, that `Person.inbox_url` is actually nullable. For instance, if you check, https://lemmy.world/api/v3/post/list?sort=Active, you'll notice that all of the `PostView.creator` objects are missing `inbox_url` fields.

**Comment by TheBrokenRail** [comment]
Also `Community.followers_url` and `Community.inbox_url` are mislabeled. It seems #160 added these definitions.

Also, I'm using `lemmy-js-client` v0.18.3 with Lemmy v0.18.4, so it should be compatible.

**Comment by dessalines** [comment]
These type definitions are auto-generated from the rust code, using ts-rs. It seems to be using a `default of `placeholder_url`:  https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/src/source/person.rs#L47

@Nutomic is this a non-issue then? Or should inbox_url be made optional?

**Comment by Nutomic** [comment]
[A while ago](https://github.com/LemmyNet/lemmy/pull/2767) we marked them as `#[serde(skip)]` in Rust so they dont get sent over the api, because they are really only needed for federation. The placeholder was added because this was causing problems for the Rust client api (https://github.com/LemmyNet/lemmy/pull/3362). [Here is the same issue reported in ts-rs](https://github.com/Aleph-Alpha/ts-rs/issues/107). Looks like we need to add `#[ts(skip)` in those cases. Im opening a PR for this.

**Comment by TheBrokenRail** [comment]
This seems to have been fixed in #181.
